apiVersion: v1
kind: Service
metadata:
  name: netdbg-server
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: netdbg-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: netdbg-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netdbg-server
  template:
    metadata:
      labels:
        app: netdbg-server
    spec:
      containers:
      - name: netdbg-server
        image: toimela/netdbg:0.0.1
        ports:
        - containerPort: 80
